#!/usr/bin/env ruby

require_relative 'lib/primes'
require_relative 'lib/table_printer'

if ARGV && ARGV.size == 1 && ARGV[0].to_i > 0
  n = ARGV[0].to_i

  puts "Generating table for the first #{n} primes.\n\n"
  primes = Primes.first(n)
  TablePrinter.new(primes).print

  puts "\n\n"
else
  puts %{  usage: #{$0} N
                            N is the number of primes to make a table for }
  exit -1
end
